branch-defaults:
  master:
    environment: light-hms-service-dev
    group_suffix: null
global:
  application_name: light-hms-service
  branch: null
  default_ec2_keyname: aws-india
  default_platform: Java 8
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
