spring:
  profiles: staging
---
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://database-1.cjgtz6xctubv.ap-south-1.rds.amazonaws.com:5432/postgres}
    username: ${DATASOURCE_USERNAME:hmsadmin}
    password: ${DATASOURCE_PASSWORD:hmspassword}
    validation-query: select 1
    connection-test-query: select 1
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 20000
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true